# Generated by Django 5.0.2 on 2024-02-29 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='linea',
            name='pub_date',
        ),
    ]
