# Generated by Django 5.0.2 on 2024-02-29 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0002_remove_linea_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='linea',
            name='distancia',
            field=models.IntegerField(default=0),
        ),
    ]
