# Generated by Django 5.0.2 on 2024-02-29 19:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0003_linea_distancia'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='fecha',
            field=models.DateField("date published"),
        ),
    ]
