# Generated by Django 5.0.2 on 2024-02-29 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0012_alter_incidencia_fecha'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='incidencia',
            name='fecha',
        ),
    ]
