# Generated by Django 5.0.2 on 2024-02-29 20:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidencias', '0013_remove_incidencia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='incidencia',
            name='fecha',
            field=models.DateTimeField("date published"),
        ),
    ]
